//Actions
//Products
export const ADD_PRODUCT_TO_SLOT_STOCK = 'ADD_PRODUCT_TO_SLOT_STOCK';
export const REMOVE_PRODUCT_FROM_SLOT_STOCK = 'REMOVE_PRODUCT_FROM_SLOT_STOCK';

//Machines
export const ADD_VENDING_MACHINE = 'ADD_VENDING_MACHINE';
export const REMOVE_VENDING_MACHINE = 'REMOVE_VENDING_MACHINE';
export const ADD_ROW = 'ADD_ROW';
export const REMOVE_ROW = 'REMOVE_ROW';
export const ADD_COLUMN = 'ADD_COLUMN';
export const REMOVE_COLUMN = 'REMOVE_COLUMN';
export const ADD_SLOT = 'ADD_SLOT';
export const REMOVE_SLOT = 'REMOVE_SLOT';
export const SHOW_PRODUCT_SELECTION_PANEL = 'SHOW_PRODUCT_SELECTION_PANEL';
export const HIDE_PRODUCT_SELECTION_PANEL = 'HIDE_PRODUCT_SELECTION_PANEL';
export const SELECT_TARGET_SLOT = 'SELECT_TARGET_SLOT';
export const ADD_PRODUCT_TO_SLOT = 'ADD_PRODUCT_TO_SLOT';
export const REMOVE_PRODUCT_FROM_SLOT = 'REMOVE_PRODUCT_FROM_SLOT';